// Code generated by "stringer -type NValue ."; DO NOT EDIT.

package argh

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OneOrMoreValue - -2]
	_ = x[ZeroOrMoreValue - -1]
	_ = x[ZeroValue-0]
}

const _NValue_name = "OneOrMoreValueZeroOrMoreValueZeroValue"

var _NValue_index = [...]uint8{0, 14, 29, 38}

func (i NValue) String() string {
	i -= -2
	if i < 0 || i >= NValue(len(_NValue_index)-1) {
		return "NValue(" + strconv.FormatInt(int64(i+-2), 10) + ")"
	}
	return _NValue_name[_NValue_index[i]:_NValue_index[i+1]]
}
